volumio/volumio-plugins-sources

fusion/i18n/strings_en.json, fusion/i18n/strings_fr.json, fusion/index.js, fusion/install.sh, fusion/mpdignore, fusion/package.json, fusion/readme.md, fusion/uninstall.sh
=> FusionDsp - code cleaning

soundcloud/README.md, soundcloud/index.js, soundcloud/lib/controller/browse/index.js, soundcloud/lib/controller/browse/view-handlers/base.js, soundcloud/lib/controller/browse/view-handlers/explodable.js, soundcloud/lib/controller/browse/view-handlers/factory.js, soundcloud/lib/controller/browse/view-handlers/playlist.js, soundcloud/lib/controller/browse/view-handlers/root.js, soundcloud/lib/controller/browse/view-handlers/track.js, soundcloud/lib/controller/play/index.js, soundcloud/lib/controller/search/index.js, soundcloud/lib/helper/view.js, soundcloud/package.json
- [Fixed] Adding current song to playlist / favorites in Playback view
- [Added] Go To Album / Artist
- [Changed] Use plain text titles if Manifest UI is enabled
=> Update SoundCloud plugin 0.1.4

index.js, volusonic/backend.js, volusonic/config.json, volusonic/i18n/strings_en.json, volusonic/package.json
- Genre lists now show complete album list
- default size list is now 500
- artist page adaptation for the manifest theme
=> [volusonic] genre list improvement and manifest adaptation

minidlna/UIConfig.json, minidlna/index.js, minidlna/install.sh, minidlna/package.json
Added handling of failures that might happen while processing install.sh. In that case cleanup including removing software packages which might already have been installed .
=> miniDLNA 3.1.12

rotaryencoder2/index.js, rotaryencoder2/package-lock.json, rotaryencoder2/package.json
Bugfix for bug reported here: 
https://community.volumio.org/t/plugin-rotaryencoder-ii/48538/86
=> rotaryencoder2  1.0.12

fusion/index.js, fusion/package.json, fusion/readme.md
filter fix if freq<samplerate/2
misc warning for DRC FIR
update tools
=> FusionDsp- ready for stable

fusion/index.js, fusion/package.json, fusion/readme.md
=> FusionDsp- preset naming for each mode

touch_display/README.md, touch_display/UIConfig.json, touch_display/index.js, touch_display/install.sh, touch_display/package.json, touch_display/uninstall.sh
PR fixes
1. [ineffective prevention of installation on primo](https://github.com/volumio/volumio-plugins-sources/pull/210#issuecomment-1536534461).
2. [missing options](https://community.volumio.org/t/plugin-touch-display/10647/585) on the plugin's configuration page.
=> Touch Display 3.3.7

podcast/index.js, podcast/package.json
=> feat(podcast): render episode date in navigator

ir_controller/README.md, ir_controller/UIConfig.json, ir_controller/configurations/Panasonic EUR643824/lircd.conf, ir_controller/configurations/Panasonic EUR643824/lircrc, ir_controller/configurations/Pioneer CU-PD053/lircd.conf, ir_controller/configurations/Pioneer CU-PD053/lircrc, ir_controller/configurations/Technics RAK-SL948WK/lircd.conf, ir_controller/configurations/Technics RAK-SL948WK/lircrc, ir_controller/index.js, ir_controller/install.sh, ir_controller/package.json, ir_controller/uninstall.sh
Added configuration files for "Panasonic EUR643824", "Pioneer CU-PD053" and "Technics RAK-SL948WK"; fix for Odroid C1/C2/C4/N2 not loading "meson-ir" module
=> IR Controller 3.4.10

calmradio/index.js, calmradio/package.json
corrects failure during search
=> CalmRadio version 1.2.4

ir_controller/README.md, ir_controller/configurations/NAD AMP 3/lircd.conf, ir_controller/configurations/NAD AMP 3/lircrc, ir_controller/configurations/Pro-Ject Control it Pre Box S2 Digital/lircd.conf, ir_controller/configurations/Pro-Ject Control it Pre Box S2 Digital/lircrc, ir_controller/configurations/Tmall Magic Box 1S Remote Control/lircd.conf, ir_controller/configurations/Tmall Magic Box 1S Remote Control/lircrc, ir_controller/package.json
Added configuration files for "NAD AMP 3", "Pro-Ject Control it Pre Box S2 Digital" and "Tmall Magic Box 1S Remote Control".
=> IR Controller 3.4.11

motherearthradio/index.js, motherearthradio/motherearthlogo.svg, motherearthradio/package-lock.json, motherearthradio/package.json, motherearthradio/radio_stations.json
updated to https streaming, fixed Instrumental AAC stream erroneously playing FLAC stream
=> Mother Earth Radio 1.1.0

volusonic/i18n/strings_en.json, volusonic/i18n/strings_fr.json, volusonic/index.js, volusonic/package.json
=> added favorites management

motherearthradio/index.js, motherearthradio/package.json, motherearthradio/radio_stations.json
added Mother Earth Jazz channel
=> 1.2.1 motherearthradio

spotify/index.js
related: https://github.com/volumio/volumio-plugins-sources/pull/259
=> fix(spotify): remove references to missing method

spotify/index.js
https://community.volumio.com/t/new-2023-spotify-plugin/63381/41
=> feat(spotify): set limit 50 for "my playlists"

spotify/UIConfig.json
=> fix(spotify): remove duplicated UI config normalization value

fusion/camilladsp-js.js
Attempt to fix a possible problem raised in a forum thread: https://community.volumio.com/t/fusiondsp-the-complete-dsp-center-for-volumio3/50474/1093
Note: I make this PR as draft, this is a possible fix to a problem I was not yet able to reproduce on mp1 device.
=> fusiondsp: attempt to fix consumed seconds on track begin

fusion/camilladsp-pure.conf.yml, fusion/index.js
Pure camilladsp GUI at the moment does not work with the recent changes on process startup code.
This PR fixes the behaviour refactoring the `createCamilladspfile()` function and splitting the two paths when camilladsp GUI is in exclusive use or not.
=> Fix pure camilla GUI

remotepi/UIConfig.json, remotepi/index.js, remotepi/package.json
Fixed incaccurate line feed handling when modifying "/boot/userconfig.txt"; added Pi5 detection and warning
=> RemotePi 3.2.1

ir_controller/README.md, ir_controller/configurations/Argon Remote/lircd.conf, ir_controller/configurations/Argon Remote/lircrc, ir_controller/configurations/Pioneer CU-PD053/lircd.conf, ir_controller/index.js, ir_controller/package.json
Added configuration files for "Argon Remote"; corrected "lircd.conf" for "Pioneer CU-PD0053".
=> IR Controller 3.4.12

ir_controller/README.md, ir_controller/UIConfig.json, ir_controller/configurations/Aiyima T9 Pro/lircd.conf, ir_controller/configurations/Aiyima T9 Pro/lircrc, ir_controller/configurations/Technics RAK-SL948WK/lircrc, ir_controller/i18n/strings_de.json, ir_controller/i18n/strings_en.json, ir_controller/i18n/strings_fr.json, ir_controller/i18n/strings_nl.json, ir_controller/index.js, ir_controller/package.json
- added switch to show/hide advanced parameters for GPIO configuration
- added configuration files for "Aiyima T9 Pro"
- corrected typo in "lircrc" for "Technics RAK-SL948WK"
=> IR Controller 3.4.13

radio_paradise/package.json, radio_paradise/radio_stations.json
I would like to add two streams into the radio_paradise plugin.
=> radio_paradise_add_streams

gpio_control/UIConfig.json, gpio_control/i18n/strings_en.json, gpio_control/index.js, gpio_control/package-lock.json, gpio_control/package.json
Added gpiox library to gpio_control v1.0.10
Fixed link to forum
Increased version number
Increased gpiox library to latest version
Disabled logging
=> Added gpiox library to gpio_control v1.0.10

ampswitch/index.js, ampswitch/package-lock.json, ampswitch/package.json
Credits: @SanKen
https://community.volumio.com/t/3-779-appears-to-have-broken-amp-switch-for-me/69712/7
=> Amplifier Switch v 0.2.1

podcast/podcasts_list.json
=> added Questions in Finance

pirateaudio/display.py, pirateaudio/package-lock.json, pirateaudio/package.json
Changed GPIO input method to a threaded polling system.
=> pirateaudio GPIO Hotfix: Added polling thread for compatibility.
